[package]
name = "luminjs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
thiserror = "1.0"
anyhow = "1.0"
serde = "=1.0.197"
serde_json = "1.0"
owo-colors = "4.0"
swc_common = "0.33"
swc_ecma_parser = "0.143"
swc_ecma_ast = "0.112"

[dev-dependencies]
pretty_assertions = "1.4"
tempfile = "3.10"
